
apiVersion: iam.kubesphere.io/v1alpha2
kind: GlobalRole
metadata:
  annotations:
    iam.kubesphere.io/aggregation-roles: '["role-template-manage-app-templates","role-template-view-app-templates","role-template-manage-clusters","role-template-view-clusters","role-template-view-workspaces","role-template-manage-workspaces-newdefine","role-template-view-users","role-template-manage-users","role-template-view-roles","role-template-manage-roles"]'
    kubesphere.io/creator: admin
  name: workspaces-manager
spec: 
  IsDefault: "1"
rules:
- apiGroups:
  - '*'
  resources:
  - abnormalworkloads
  - quotas
  - workloads
  - volumesnapshots
  - dashboards
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - persistentvolumeclaims
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  - applications
  - controllerrevisions
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  - meshpolicies
  - cronjobs
  - jobs
  - devopsprojects
  - devops
  - pipelines
  - pipelines/runs
  - pipelines/pipelineruns
  - pipelines/branches
  - pipelines/checkScriptCompile
  - pipelines/consolelog
  - pipelines/scan
  - pipelines/sonarstatus
  - pipelineruns
  - pipelineruns/nodedetails
  - checkCron
  - credentials
  - credentials/usage
  - s2ibinaries
  - s2ibinaries/file
  - s2ibuilders
  - s2ibuildertemplates
  - s2iruns
  - events
  - ingresses
  - router
  - filters
  - pods
  - pods/log
  - pods/exec
  - pods/containers
  - namespacenetworkpolicies
  - workspacenetworkpolicies
  - networkpolicies
  - podsecuritypolicies
  - rolebindings
  - roles
  - members
  - servicepolicies
  - federatedapplications
  - federatedconfigmaps
  - federateddeployments
  - federatedingresses
  - federatedjobs
  - federatedlimitranges
  - federatednamespaces
  - federatedpersistentvolumeclaims
  - federatedreplicasets
  - federatedsecrets
  - federatedserviceaccounts
  - federatedservices
  - federatedservicestatuses
  - federatedstatefulsets
  - groups
  - groupbindings
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - federatedworkspaces
  - workspaces
  - workspaceroles
  - workspacemembers
  - workspacemembers/namespaces
  - workspacemembers/devops
  - workspacerolebindings
  verbs:
  - list
  - get
  - watch 
- apiGroups:
  - '*'
  resources:
  - users
  - users/password
  - users/loginrecords
  - globalroles
  verbs:
  - '*'
- apiGroups:
  - openpitrix.io
  resources:
  - repos
  - apps
  - apps/versions
  - categories
  - apps/audits
  - clusters/applications
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - clusters
  - cluster
  verbs:
  - list
- apiGroups:
  - monitoring.kubesphere.io
  - monitoring.coreos.com
  - metering.kubesphere.io
  - servicemesh.kubesphere.io
  - alerting.kubesphere.io
  - network.kubesphere.io
  - resources.kubesphere.io
  resources:
  - '*'
  verbs:
  - '*'