  apiVersion: iam.kubesphere.io/v1alpha2
  kind: GlobalRole
  metadata:
    annotations:
      iam.kubesphere.io/aggregation-roles: '["role-template-view-app-templates"]'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"iam.kubesphere.io/v1alpha2","kind":"GlobalRole","metadata":{"annotations":{"iam.kubesphere.io/aggregation-roles":"[\"role-template-view-app-templates\"]","kubesphere.io/creator":"admin"},"name":"platform-regular"},"rules":[]}
      kubesphere.io/creator: admin
    generation: 1
    labels:
      kubefed.io/managed: "false"
    name: platform-regular
  spec: 
    IsDefault: "1"
  rules: []